#!/usr/bin/env python
# coding: utf-8

# # Import Libraries
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


# # Read Dataset
data = pd.read_csv('/Users/manishsandil/spyder_data/50_Startups.csv')

# # Prepare Input and Target
X = data.drop(['Profit','State'],axis=1)
y = data['Profit']
print(X.shape,y.shape)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.20,random_state=5)


# # Instantiate and Fit Model with training data

lmodel = LinearRegression()
lmodel.fit(X_train,y_train)


# # Start Predicting
y_train_pred = lmodel.predict(X_train)
y_test_pred = lmodel.predict(X_test)

df = pd.DataFrame(y_test_pred,y_test)
print(df)

mse = mean_squared_error(y_test,y_test_pred)
print(np.sqrt(mse))

